# Generated by Django 5.0.3 on 2024-05-06 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('mobileNumber', models.BigIntegerField(blank=True, null=True)),
                ('password', models.CharField(max_length=128)),
                
                ('healthComplication', models.CharField(max_length=3, choices=[
                    ('yes', 'I have health complications'),
                    ('no', 'I do not have health complications')    
                ], default='no')),
            ],
        ),
    ]
