# Generated by Django 5.0.3 on 2024-06-14 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapi', '0002_addproduct_loginuser_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addproduct',
            name='barcode',
            field=models.IntegerField(null=True),
        ),
    ]
