# Generated by Django 5.0.6 on 2024-06-14 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapi', '0003_signup_illness'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='illness2',
            field=models.CharField(choices=[('respiratory', 'Respiratory Infections'), ('hypertension', 'Hypertension'), ('uti', 'Urinary Tract Infection'), ('animal', 'Animal Bites'), ('skin', 'Skin Diseases'), ('pneumonia', 'Pneumonia'), ('diarrhea', 'Diarrhea')], default='respiratory', max_length=50),
        ),
        migrations.AddField(
            model_name='signup',
            name='illness3',
            field=models.CharField(choices=[('respiratory', 'Respiratory Infections'), ('hypertension', 'Hypertension'), ('uti', 'Urinary Tract Infection'), ('animal', 'Animal Bites'), ('skin', 'Skin Diseases'), ('pneumonia', 'Pneumonia'), ('diarrhea', 'Diarrhea')], default='respiratory', max_length=50),
        ),
    ]
