# Generated by Django 5.0.3 on 2024-06-14 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapi', '0003_addproduct_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproduct',
            name='barcode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
