# Generated by Django 5.0.3 on 2024-06-05 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapi', '0005_loginuser_groups_loginuser_user_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ingredients', models.TextField()),
                ('nutritional_facts', models.TextField()),
                ('image', models.ImageField(upload_to='djangoapi/ProductImage')),
            ],
        ),
    ]
