# Generated by Django 5.0.3 on 2024-06-14 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapi', '0005_alter_addproduct_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproduct',
            name='barcode',
            field=models.CharField(max_length=13, null=True),
        ),
    ]
