# Generated by Django 5.0.3 on 2024-06-14 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapi', '0004_signup_illness2_signup_illness3'),
        ('djangoapi', '0006_alter_addproduct_barcode'),
    ]

    operations = [
    ]
