# Generated by Django 5.0.6 on 2024-06-17 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapi', '0007_merge_20240614_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='illness',
            field=models.CharField(choices=[('respiratory', 'Respiratory Infections'), ('hypertension', 'Hypertension'), ('uti', 'Urinary Tract Infection'), ('animal', 'Animal Bites'), ('skin', 'Skin Diseases'), ('pneumonia', 'Pneumonia'), ('diarrhea', 'Diarrhea'), ('null', '')], default='null', max_length=50),
        ),
        migrations.AlterField(
            model_name='signup',
            name='illness2',
            field=models.CharField(choices=[('respiratory', 'Respiratory Infections'), ('hypertension', 'Hypertension'), ('uti', 'Urinary Tract Infection'), ('animal', 'Animal Bites'), ('skin', 'Skin Diseases'), ('pneumonia', 'Pneumonia'), ('diarrhea', 'Diarrhea'), ('null2', '')], default='null2', max_length=50),
        ),
        migrations.AlterField(
            model_name='signup',
            name='illness3',
            field=models.CharField(choices=[('respiratory', 'Respiratory Infections'), ('hypertension', 'Hypertension'), ('uti', 'Urinary Tract Infection'), ('animal', 'Animal Bites'), ('skin', 'Skin Diseases'), ('pneumonia', 'Pneumonia'), ('diarrhea', 'Diarrhea'), ('null3', '')], default='null', max_length=50),
        ),
        migrations.AlterField(
            model_name='signup',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
