# Generated by Django 5.0.3 on 2024-06-21 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapi', '0008_alter_signup_illness_alter_signup_illness2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addproduct',
            name='category',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
