# Generated by Django 5.0.3 on 2024-06-21 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapi', '0009_addproduct_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproduct',
            name='category',
            field=models.CharField(choices=[('beverages', 'Beverages'), ('junk food', 'Junk Food'), ('ice cream', 'Ice Cream'), ('frozen goods', 'Frozen Goods'), ('pastry', 'Pastry'), ('noodles/pasta', 'Noodles/Pasta'), ('instant noodles', 'Instant Noodles'), ('nibbles', 'Nibbles'), ('coffee/milk', 'Coffee/Milk'), ('biscuits', 'Biscuits'), ('candies', 'Candies'), ('liqour/wines', 'Liqour/Wines'), ('canned goods', 'Canned Goods')], max_length=50, null=True),
        ),
    ]
