# Generated by Django 5.0.4 on 2024-06-25 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapi', '0010_alter_addproduct_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproduct',
            name='category',
            field=models.CharField(choices=[('beverages', 'Beverages'), ('junk food', 'Junk Food'), ('ice cream', 'Ice Cream'), ('frozen goods', 'Frozen Goods'), ('pastry', 'Pastry'), ('noodles/pasta', 'Noodles/Pasta'), ('condiments', 'Condiments'), ('instant noodles', 'Instant Noodles'), ('powder juice', 'Powder Juice'), ('oil section', 'Oil Section'), ('bread spread', 'Bread Spread'), ('nibbles', 'Nibbles'), ('coffee/milk', 'Coffee/Milk'), ('biscuits', 'Biscuits'), ('candies', 'Candies'), ('liqour/wines', 'Liqour/Wines'), ('chocolates', 'Chocolates'), ('diswashing/laundry', 'Diswashing/Laundry'), ('toiletries', 'Toiletries'), ('party utensils', 'Party Utensils'), ('canned goods', 'Canned Goods')], max_length=50, null=True),
        ),
    ]
