# Generated by Django 5.0.6 on 2024-07-02 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapi', '0010_alter_addproduct_category_alter_signup_illness_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginuser',
            name='liked_products',
            field=models.ManyToManyField(blank=True, related_name='liked_by', to='djangoapi.addproduct'),
        ),
    ]
