# Generated by Django 5.0.6 on 2024-07-02 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapi', '0011_loginuser_liked_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='liked_products',
            field=models.ManyToManyField(blank=True, related_name='liked_by_users', to='djangoapi.addproduct'),
        ),
    ]
