# Generated by Django 5.0.6 on 2024-07-02 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapi', '0011_alter_addproduct_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproduct',
            name='category',
            field=models.CharField(choices=[('beverages', 'Beverages'), ('junk food', 'Junk Food'), ('ice cream', 'Ice Cream'), ('frozen goods', 'Frozen Goods'), ('pastry', 'Pastry'), ('water', 'Water'), ('condiments', 'Condiments'), ('noodles pasta', 'NoodlesPasta'), ('instant noodles', 'InstantNoodles'), ('powdered juice', 'Powdered Juice'), ('oil section', 'Oil Section'), ('bread spread', 'Bread Spread'), ('canned goods', 'Canned Goods'), ('nibbles', 'Nibbles'), ('coffee/milk', 'Coffee/Milk'), ('biscuits', 'Biscuits'), ('candies', 'Candies'), ('chocolates', 'Chocolates'), ('liqour/wines', 'Liqour/Wines'), ('party utensils', 'Party Utensils'), ('toiletries', 'Toiletries'), ('diswashing/laundry', 'Diswashing/Laundry')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='signup',
            name='illness',
            field=models.CharField(choices=[('respiratory', 'Respiratory Infections'), ('hypertension', 'Hypertension'), ('uti', 'Urinary Tract Infection'), ('diabetes', 'Diabetes'), ('skin', 'Skin Diseases'), ('pneumonia', 'Pneumonia'), ('diarrhea', 'Diarrhea'), ('null', '')], default='null', max_length=50),
        ),
        migrations.AlterField(
            model_name='signup',
            name='illness2',
            field=models.CharField(choices=[('respiratory', 'Respiratory Infections'), ('hypertension', 'Hypertension'), ('uti', 'Urinary Tract Infection'), ('diabetes', 'Diabetes'), ('skin', 'Skin Diseases'), ('pneumonia', 'Pneumonia'), ('diarrhea', 'Diarrhea'), ('null2', '')], default='null2', max_length=50),
        ),
        migrations.AlterField(
            model_name='signup',
            name='illness3',
            field=models.CharField(choices=[('respiratory', 'Respiratory Infections'), ('hypertension', 'Hypertension'), ('uti', 'Urinary Tract Infection'), ('diabetes', 'Diabetes'), ('skin', 'Skin Diseases'), ('pneumonia', 'Pneumonia'), ('diarrhea', 'Diarrhea'), ('null3', '')], default='null3', max_length=50),
        ),
    ]
