# Generated by Django 5.0.6 on 2024-07-02 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapi', '0012_alter_addproduct_category_alter_signup_illness_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addproduct',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_products', to='djangoapi.signup'),
        ),
    ]
