# Generated by Django 5.0.6 on 2024-07-08 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapi', '0012_signup_liked_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='addproduct',
            name='glb_file',
            field=models.FileField(blank=True, help_text='Upload a .glb file', null=True, upload_to='djangoapi/GLBFiles'),
        ),
    ]
