# Generated by Django 5.0.6 on 2024-07-11 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapi', '0014_addproduct_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='signup',
            options={'verbose_name': 'Product'},
        ),
    ]
