# Generated by Django 5.0.3 on 2024-07-13 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapi', '0016_alter_addproduct_options_alter_signup_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='illness',
            field=models.CharField(choices=[('kidney diseases', 'Kidney Diseases'), ('hypertension', 'Hypertension'), ('uti', 'Urinary Tract Infection'), ('diabetes', 'Diabetes'), ('skin', 'Skin Diseases'), ('gastrointestinal', 'Gastrointestinal Diseases'), ('liver diseases', 'Liver Diseases'), ('null', '')], default='null', max_length=50),
        ),
        migrations.AlterField(
            model_name='signup',
            name='illness2',
            field=models.CharField(choices=[('kidney diseases', 'Kidney Diseases'), ('hypertension', 'Hypertension'), ('uti', 'Urinary Tract Infection'), ('diabetes', 'Diabetes'), ('skin', 'Skin Diseases'), ('gastrointestinal', 'Gastrointestinal Diseases'), ('liver diseases', 'Liver Diseases'), ('null2', '')], default='null2', max_length=50),
        ),
        migrations.AlterField(
            model_name='signup',
            name='illness3',
            field=models.CharField(choices=[('kidney diseases', 'Kidney Diseases'), ('hypertension', 'Hypertension'), ('uti', 'Urinary Tract Infection'), ('diabetes', 'Diabetes'), ('skin', 'Skin Diseases'), ('gastrointestinal', 'Gastrointestinal Diseases'), ('liver diseases', 'Liver Diseases'), ('null3', '')], default='null3', max_length=50),
        ),
    ]
