# Generated by Django 5.0.3 on 2024-07-16 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapi', '0017_alter_signup_illness_alter_signup_illness2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='illness',
            field=models.CharField(choices=[('kidney', 'Kidney Diseases'), ('hypertension', 'Hypertension'), ('uti', 'Urinary Tract Infection'), ('diabetes', 'Diabetes'), ('skin', 'Skin Diseases'), ('gastrointestinal', 'Gastrointestinal Diseases'), ('liver', 'Liver Diseases'), ('null', '')], default='null', max_length=50),
        ),
        migrations.AlterField(
            model_name='signup',
            name='illness2',
            field=models.CharField(choices=[('kidney', 'Kidney Diseases'), ('hypertension', 'Hypertension'), ('uti', 'Urinary Tract Infection'), ('diabetes', 'Diabetes'), ('skin', 'Skin Diseases'), ('gastrointestinal', 'Gastrointestinal Diseases'), ('liver', 'Liver Diseases'), ('null2', '')], default='null2', max_length=50),
        ),
        migrations.AlterField(
            model_name='signup',
            name='illness3',
            field=models.CharField(choices=[('kidney', 'Kidney Diseases'), ('hypertension', 'Hypertension'), ('uti', 'Urinary Tract Infection'), ('diabetes', 'Diabetes'), ('skin', 'Skin Diseases'), ('gastrointestinal', 'Gastrointestinal Diseases'), ('liver', 'Liver Diseases'), ('null3', '')], default='null3', max_length=50),
        ),
    ]
