# Generated by Django 5.0.3 on 2024-07-16 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapi', '0018_alter_signup_illness_alter_signup_illness2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproduct',
            name='image',
            field=models.ImageField(upload_to='djangoapi/ProductImage/'),
        ),
    ]
