# Generated by Django 5.0.3 on 2024-07-16 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapi', '0019_alter_addproduct_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproduct',
            name='image',
            field=models.ImageField(upload_to='djangoapi/ProductImage'),
        ),
    ]
